import './index.scss';
import { Button } from './components/button';

new Button(undefined, 'Packman', () => location.href="/packman.html");
new Button(undefined, 'Sea battle', () => location.href="sea_battle.html");
new Button(undefined, 'Hw 1', () => location.href="/hw_1.html");
new Button(undefined, 'Hw 2-3', () => location.href="/hw_2-3.html");
new Button(undefined, 'Hw 5 part 1', () => location.href="/hw_5_part_1.html");
new Button(undefined, 'Hw 5 part 2', () => location.href="/hw_5_part_2.html");
new Button(undefined, 'Hw 5 part 3', () => location.href="/hw_5_part_3.html");
new Button(undefined, 'Hw 5 part 4', () => location.href="/hw_5_part_4.html");
new Button(undefined, 'Hw 6', () => location.href="/hw_6.html");
new Button(undefined, 'Hw 11', () => location.href="/hw_11.html");
new Button(undefined, 'Practice 5', () => location.href="/practice_5.html");
new Button(undefined, 'Lesson 12', () => location.href="/lesson_12.html");
new Button(undefined, 'Hw 12', () => location.href="/hw_12.html");
new Button(undefined, 'Lesson 13', () => location.href="/lesson_13.html");
new Button(undefined, 'Lesson 14', () => location.href="/lesson_14.html");
new Button(undefined, 'Hw 14', () => location.href="/hw_14.html");
new Button(undefined, 'Lesson 15', () => location.href="/lesson_15.html");
new Button(undefined, 'Hw 16', () => location.href="/hw_16.html");
new Button(undefined, 'Lesson 17', () => location.href="/lesson_17.html");
new Button(undefined, 'Hw 17', () => location.href="/hw_17.html");
new Button(undefined, 'spa', () => location.href="/spa.html");